version: '3'

services:
  jak-onlineshop-database:
    container_name: jak-onlineshop-database
    image: postgres
    environment:
      # Notice: User, Password and Database will automatically be created according to the env variables
      - POSTGRES_USER=onlineshop_user
      - POSTGRES_PASSWORD=shop_12345
      - POSTGRES_DB=jak_onlineshop
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - jak-onlineshop-network
    restart: on-failure

  jak-onlineshop-webapp:
    container_name: jak-onlineshop-webapp
    image: fabiandiemand/glassfish-postgres-image:latest
    volumes:
      # Mount the .war from the host to the autodeploy directory in the docker glassfish container
      - ./../build/libs/tech2go.war:/usr/local/glassfish/glassfish/domains/domain1/autodeploy/tech2go.war
    ports:
      - "8080:8080"
      - "4848:4848"
      - "8181:8181"
    depends_on:
      - jak-onlineshop-database
    networks:
      - jak-onlineshop-network
    restart: on-failure

networks:
  jak-onlineshop-network:
    driver: bridge

volumes:
  postgres: